//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFA.Models
{
    internal class BookmarkItemView
    {
        private DBEntities dB;
        private Bookmark bookmark;
        private User viewer;

        public BookmarkItemView(DBEntities dB, Bookmark bookmark, User viewer)
        {
            this.dB = dB;
            this.bookmark = bookmark;
            this.viewer = viewer;
        }

        public object OwnerShip { get; internal set; }
        public object Url { get; internal set; }
        public object Name { get; internal set; }
        public object Category { get; internal set; }
    }
}