//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFA.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Bookmark
    {
        
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int UserId { get; set; }
        public bool Shared { get; set; }
        public Nullable<int> CategoryId { get; set; }

        public virtual Category Category { get; set; }
        public virtual User User { get; set; }

        public static Bookmark FromBookmarkView(BookmarkView bookmarkView, bool updating = false)
        {
            DBEntities db = new DBEntities();
            Bookmark bookmark = new Bookmark();

            if (updating)
            {
                bookmark.Id = bookmarkView.Id;
                bookmark.UserId = bookmarkView.OwnerId;
            }
            else
            {
                bookmark.Id = FindNextId();
                bookmark.UserId = OnlineUsers.GetSessionUser().Id;
            }
            bookmark.CategoryId = GetCategoryIdFromBookmarkView(bookmarkView);
            bookmark.Name = bookmarkView.Name;
            bookmark.Url = bookmarkView.Url;
            bookmark.Shared = bookmarkView.Shared;

            return bookmark;
        }

        public static int FindNextId()
        {
            DBEntities db = new DBEntities();
            int count = 0;
            foreach (Bookmark b in db.Bookmarks)
            {
                count++;
            }
            return count + 1;
        }

        public static int? GetCategoryIdFromBookmarkView(BookmarkView bookmarkView)
        {
            DBEntities db = new DBEntities();

            int? id = null;

            if (bookmarkView.CategoryId.HasValue)
            {
                id = bookmarkView.CategoryId;
            }
            else if (db.CategoryExist(bookmarkView.CategoryName))
            {
                id = db.Categories.Where(x => x.Name == bookmarkView.CategoryName).First().Id;
            }
            else if(!bookmarkView.CategoryId.HasValue && bookmarkView.CategoryName == null)
            {
                id = null;
            }
            else
            {
                id = CreateCategory(bookmarkView);
            }
            return id;
        }

        public static int CreateCategory(BookmarkView bookmarkView)
        {
            DBEntities db = new DBEntities();
            Category category = new Category();

            int count = 0;
            foreach (Category c in db.Categories)
            {
                count++;
            }
            category.Id = count + 1;

            category.Name = bookmarkView.CategoryName;

            db.Categories.Add(category);
            db.SaveChanges();

            return category.Id;
        }


        public BookmarkView CreateBookmarkView()
        {
            BookmarkView bookmarkView = new BookmarkView();
            bookmarkView.Id = Id;
            bookmarkView.Name = Name;
            bookmarkView.Url = Url;
            bookmarkView.Shared = Shared;
            bookmarkView.OwnerId = UserId;
            bookmarkView.CategoryId = CategoryId;
            return bookmarkView;
        }
        public void UpdateWithBookmarkView(BookmarkView bookmarkView)
        {
            Id = bookmarkView.Id;
            Name = bookmarkView.Name;
            Url = bookmarkView.Url;
            Shared = bookmarkView.Shared;
            UserId = bookmarkView.OwnerId;
            CategoryId = bookmarkView.CategoryId;
        }
        public void UpdateWithBookmark(Bookmark bookmark)
        {
            Id = bookmark.Id;
            Name = bookmark.Name;
            Url = bookmark.Url;
            Shared = bookmark.Shared;
            UserId = bookmark.UserId;
            CategoryId = bookmark.CategoryId;
        }
        public void Update(Bookmark bookmark)
        {
            Id = bookmark.Id;
            Name = bookmark.Name;
            Url = bookmark.Url;
            Shared = bookmark.Shared;
            UserId = bookmark.UserId;
            CategoryId = bookmark.CategoryId;
        }
    }
    public class BookmarkView
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(32)]
        public string Name { get; set; }

        [Required]
        [MaxLength(128)]
        [DataType(DataType.Url)]
        public string Url { get; set; }

        [Required]
        public bool Shared { get; set; }

        public int OwnerId { get; set; }

        public string OwnerName { get; set; }
        public Nullable<int> CategoryId { get; set; } = null;
        public string newCategory { get; set; }

        public string CategoryName { get; set; }

        public IEnumerable<Category> categories = new DBEntities().Categories;

        public int? GetIdFromName(string name)
        {
            DBEntities db = new DBEntities();
            int id = 0;

            try
            {
                id = db.Categories.Find(name).Id;
            }
            catch (Exception e)
            {
               foreach(Category c in db.Categories)
               {
                    id = c.Id + 1;
               }

                db.Categories.Add(new Category(name, id));

            }

            
            return id;
        }

        public static List<BookmarkView> GetDBCollection()
        {
            DBEntities db = new DBEntities();
            List<BookmarkView> collection = new List<BookmarkView>() ;
            foreach(Bookmark b in db.Bookmarks.ToList())
            {
                string strCat;
                try
                {
                    strCat = db.Categories.Where(x => x.Id == b.CategoryId).First().Name;
                }
                catch(Exception e)
                {
                    strCat = "";
                }
                
                collection.Add(new BookmarkView {
                    Id = b.Id,
                    Name = b.Name,
                    CategoryName = strCat,
                    Shared = b.Shared,
                    OwnerName = db.Users.Where(x => x.Id == b.UserId).First().UserName,
                    Url = b.Url
                    });
            }
            return collection;
        }

        public bool HasCategory()
        {
            bool hasCategory = false;
            if(this.CategoryId.HasValue || this.CategoryName != "")
            {
                hasCategory = true;
            }
            return hasCategory;
        }
    }
    public class BookmarkItemView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string OwnerShip { get; set; }
        public string OwnerEmail { get; set; }
        public string Category { get; set; }
        public bool AllowEdit { get; set; }
        public BookmarkItemView() { }
        public BookmarkItemView(DBEntities DB, Bookmark bookmark, User viewer)
        {
            Id = bookmark.Id;
            Name = bookmark.Name;
            Url = bookmark.Url;
            if (bookmark.CategoryId != 0)
            {
                Category category = DB.Categories.Find(bookmark.CategoryId);
                if (category != null)
                {
                    Category = category.Name;
                }
            }
            else
            {
                Category = "";
            }

            AllowEdit = (viewer.Admin) || (bookmark.UserId == viewer.Id);
            if (bookmark.UserId == viewer.Id)
            {
                OwnerShip = (bookmark.Shared ? "Shared" : "Private");
                OwnerEmail = "";
            }
            else
            {
                User ownerUser = DB.Users.Find(bookmark.UserId);
                if (ownerUser != null)
                {
                    OwnerShip = ownerUser.UserName;
                    OwnerEmail = ownerUser.Email;
                }
            }
        }
    }
}
