//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFA.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Bookmarks = new HashSet<Bookmark>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public bool Admin { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Sex { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookmark> Bookmarks { get; set; }

        public void Update(User user)
        {
            this.UserName = user.UserName;
            this.FirstName = user.FirstName;
            this.LastName = user.LastName;
            this.Sex = user.Sex;
            this.BirthDate = user.BirthDate;
            this.Email = user.Email;
            this.Password = user.Password;
            this.Admin = user.Admin;
        }


        public string SexToString(int id)
        {
            string sex = "Null";

            switch (id)
            {
                case 1:
                    sex = "Male";
                    break;
                case 2:
                    sex = "Female";
                    break;
                case 3:
                    sex = "Other";
                    break;
            }
            return sex;
        }



    }
}
